name: a
favicon: null
layout_spectrum: 0.8682262112852186
typography_spectrum: 0.2172027532942593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.020799688063561916
  lightness: 0.09748177696019411
  saturation: 0.1325794153381139
  rhythmicContrast: 0.44881760864518583
purpose: []
